[package]
name = "tauri-app"
version = "0.1.0"
description = "A Tauri template project"
authors = []
license = "MIT"
repository = ""
edition = "2021"
rust-version = "1.70"

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
tauri = { version = "1.5.0", features = [ "dialog-open", "window-minimize", "window-maximize", "window-unmaximize", "window-close", "window-start-dragging" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
winreg = "0.52"
dirs = "5.0"
uuid = { version = "1.0", features = ["v4"] }
windows-sys = { version = "0.48", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_System_Diagnostics_ToolHelp", "Win32_UI_Shell", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
